Update code style

diff --git a/libexec/v-dummyimage b/libexec/v-dummyimage
--- a/libexec/v-dummyimage
+++ b/libexec/v-dummyimage
@@ -1,37 +1,39 @@
 #!/usr/bin/env bash
 #
-# github.com/VovanR/v-dummyimage
+# github.com/vovanr/v-dummyimage
+#
+# Usage: v-dummyimage <width>x<height> [image_text]
 
 
 function downloadImage {
-    size=${1}
-    text=${2}
-    imageUrl="https://dummyimage.com/"${size}"/000/fff/?text="${text}
-    fileName=${size}"-"${text}".png"
+  size=${1}
+  text=${2}
+  imageUrl="https://dummyimage.com/"${size}"/000/fff/?text="${text}
+  fileName=${size}"-"${text}".png"
 
-    wget -L ${imageUrl} -O ${fileName}
+  wget -L ${imageUrl} -O ${fileName}
 }
 
 # Arguments exists
 if [ -n "${1}" ];then
-    size=${1}
+  size=${1}
 
-    # Second argument
-    if [ -n "${2}" ];then
-        text=${2}
-        downloadImage ${size} ${text}
-    else
-        for num in {1..5}
-        do
-            downloadImage ${size} ${num}
-        done
-    fi
+  # Second argument
+  if [ -n "${2}" ];then
+    text=${2}
+    downloadImage ${size} ${text}
+  else
+    for num in {1..5}
+    do
+      downloadImage ${size} ${num}
+    done
+  fi
 else
-    echo -e "Error: Image size?"
-    echo -e "v-dummyimage 100x200 [image_text]"
-    exit 2
-    # Return 2
-    # Exit Status: Incorrect usage
+  echo -e "Error: Image size?"
+  echo -e "v-dummyimage 100x200 [image_text]"
+  exit 2
+  # Return 2
+  # Exit Status: Incorrect usage
 fi
 
 
